# Change these first
owner: innershed # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:

  - name: abelconstruction.co.uk
    url: https://abelconstruction.co.uk

  - name: abelenergy.co.uk
    url: https://abelenergy.co.uk

  - name: agaservicing.com
    url: https://agaservicing.com

  - name: allmakemotorparts.com
    url: https://allmakemotorparts.com

  - name: amispiling.co.uk
    url: https://amispiling.co.uk

  - name: angliapallets.co.uk
    url: https://angliapallets.co.uk

  - name: arwwealthmanagers.co.uk
    url: https://arwwealthmanagers.co.uk

  - name: bankboats.co.uk
    url: https://bankboats.co.uk

  - name: baybridgeinvestments.com
    url: https://baybridgeinvestments.com

  - name: beabutcher.co.uk
    url: https://beabutcher.co.uk

  - name: birdsofdereham.com
    url: https://birdsofdereham.com

  - name: bishybarnabees.co.uk
    url: https://bishybarnabees.co.uk

  - name: bmn-management.com
    url: https://bmn-management.com

  - name: boatsafetyexaminer.com
    url: https://boatsafetyexaminer.com

  - name: brundallgardensmarina.com
    url: https://brundallgardensmarina.com

  - name: burnvalleyfisheries.co.uk
    url: https://burnvalleyfisheries.co.uk

  - name: cafe7surreystreet.co.uk
    url: https://cafe7surreystreet.co.uk

  - name: calcotthall.com
    url: https://calcotthall.com

  - name: canoethebroads.co.uk
    url: https://canoethebroads.co.uk

  - name: caravanman.org.uk
    url: https://caravanman.org.uk

  - name: cavaliermailing.com
    url: https://cavaliermailing.com

  - name: coastalphotography.co.uk
    url: https://coastalphotography.co.uk

  - name: colinsquirepublishing.com
    url: https://colinsquirepublishing.com

  - name: connectafrica.net
    url: https://connectafrica.net

  - name: coopershouse.co.uk
    url: https://coopershouse.co.uk

  - name: craigdolbyracing.com
    url: https://craigdolbyracing.com

  - name: crowshall.co.uk
    url: https://crowshall.co.uk

  - name: cubane.co.uk
    url: https://cubane.co.uk

  - name: cubane.org
    url: https://cubane.org

  - name: c-u-b.com
    url: https://c-u-b.com

  - name: daisysystem.co.uk
    url: https://daisysystem.co.uk

  - name: discovernorfolk.co.uk
    url: https://discovernorfolk.co.uk

  - name: domfox.co.uk
    url: https://domfox.co.uk

  - name: edgecharter.com
    url: https://edgecharter.com

  - name: electricagaservicing.com
    url: https://electricagaservicing.com

  - name: eriba-shop.co.uk
    url: https://eriba-shop.co.uk

  - name: europeanmarinesurveys.com
    url: https://europeanmarinesurveys.com

  - name: explorewestnorfolk.com
    url: https://explorewestnorfolk.com

  - name: explorewestnorfolk.co.uk
    url: https://explorewestnorfolk.co.uk

  - name: flitzfotos.com
    url: https://flitzfotos.com

  - name: flitzfotos.co.uk
    url: https://flitzfotos.co.uk

  - name: flyingclassrooms.co.uk
    url: https://flyingclassrooms.co.uk

  - name: freshwatermarine.co.uk
    url: https://freshwatermarine.co.uk

  - name: friendsofnorwichmuseums.co.uk
    url: https://friendsofnorwichmuseums.co.uk

  - name: friendsofthenorwichmuseums.co.uk
    url: https://friendsofthenorwichmuseums.co.uk

  - name: gdscore.com
    url: https://gdscore.com

  - name: gdscore.co.uk
    url: https://gdscore.co.uk

  - name: genealogyonline.co.uk
    url: https://genealogyonline.co.uk

  - name: georgehotelswaffham.co.uk
    url: https://georgehotelswaffham.co.uk

  - name: getmyfling.co.uk
    url: https://getmyfling.co.uk

  - name: gooderstonewatergardens.co.uk
    url: https://gooderstonewatergardens.co.uk

  - name: grangetouring.co.uk
    url: https://grangetouring.co.uk

  - name: greatandlittleplumsteadparishcouncil.co.uk
    url: https://greatandlittleplumsteadparishcouncil.co.uk

  - name: greensolarfootprint.co.uk
    url: https://greensolarfootprint.co.uk

  - name: gupta-training.co.uk
    url: https://gupta-training.co.uk

  - name: homers-travel.co.uk
    url: https://homers-travel.co.uk

  - name: iafricafoundation.org
    url: https://iafricafoundation.org

  - name: ilearnabout.org
    url: https://ilearnabout.org

  - name: innershed.com
    url: https://innershed.com

  - name: investmentcatalyst.co.uk
    url: https://investmentcatalyst.co.uk

  - name: jswilsonandson.co.uk
    url: https://jswilsonandson.co.uk

  - name: justfordog.co.uk
    url: https://justfordog.co.uk

  - name: littleplumsteadbedandbreakfast.com
    url: https://littleplumsteadbedandbreakfast.com

  - name: littleplumsteadbedandbreakfast.co.uk
    url: https://littleplumsteadbedandbreakfast.co.uk

  - name: long-beach.co.uk
    url: https://long-beach.co.uk

  - name: lotribay.com
    url: https://lotribay.com

  - name: marinepowerltd.co.uk
    url: https://marinepowerltd.co.uk

  - name: mcnamara-sails.com
    url: https://mcnamara-sails.com

  - name: milnesafety.co.uk
    url: https://milnesafety.co.uk

  - name: moonshinelodge.co.uk
    url: https://moonshinelodge.co.uk

  - name: naame.co.uk
    url: https://naame.co.uk

  - name: navalarchitects.com
    url: https://navalarchitects.com

  - name: norfolkbroadsbandb.com
    url: https://norfolkbroadsbandb.com

  - name: norfolkbroads.com
    url: https://norfolkbroads.com

  - name: norfolkfhs.org.uk
    url: https://norfolkfhs.org.uk

  - name: norfolklive.org
    url: https://norfolklive.org

  - name: norfolkonlinerecordsearch.co.uk
    url: https://norfolkonlinerecordsearch.co.uk

  - name: norfolkpestcontrol.co.uk
    url: https://norfolkpestcontrol.co.uk

  - name: northnorfolk.co.uk
    url: https://northnorfolk.co.uk

  - name: norwichacupuncturerooms.co.uk
    url: https://norwichacupuncturerooms.co.uk

  - name: norwichcamping.co.uk
    url: https://norwichcamping.co.uk

  - name: norwichinns.com
    url: https://norwichinns.com

  - name: phoenixfleet.com
    url: https://phoenixfleet.com

  - name: playbarnridingcentre.co.uk
    url: https://playbarnridingcentre.co.uk

  - name: rangecleaningservices.co.uk
    url: https://rangecleaningservices.co.uk

  - name: regencyguesthouse.com
    url: https://regencyguesthouse.com

  - name: request-shed.com
    url: https://request-shed.com

  - name: riverside-holidays.co.uk
    url: https://riverside-holidays.co.uk

  - name: rwesafetyapp.co.uk
    url: https://rwesafetyapp.co.uk

  - name: sabenamarine.co.uk
    url: https://sabenamarine.co.uk

  - name: sandersonmarine.co.uk
    url: https://sandersonmarine.co.uk

  - name: sayonaravacances.co.uk
    url: https://sayonaravacances.co.uk

  - name: seadellbar.co.uk
    url: https://seadellbar.co.uk

  - name: seafoodnorthnorfolk.co.uk
    url: https://seafoodnorthnorfolk.co.uk

  - name: sequoiatreeservices.co.uk
    url: https://sequoiatreeservices.co.uk

  - name: shadowboats.co.uk
    url: https://shadowboats.co.uk

  - name: sheringhamselfcatering.co.uk
    url: https://sheringhamselfcatering.co.uk

  - name: shirtlogos.co.uk
    url: https://shirtlogos.co.uk

  - name: shredstation.co.uk
    url: https://shredstation.co.uk

  - name: shrublandsfarm.com
    url: https://shrublandsfarm.com

  - name: sloleyfarmcottages.co.uk
    url: https://sloleyfarmcottages.co.uk

  - name: southeastcoffee.co.uk
    url: https://southeastcoffee.co.uk

  - name: stills-photography.co.uk
    url: https://stills-photography.co.uk

  - name: suelamberttrust.org
    url: https://suelamberttrust.org

  - name: summercraftboats.co.uk
    url: https://summercraftboats.co.uk

  - name: superyachtconnect.com
    url: https://superyachtconnect.com

  - name: superyachtweb.com
    url: https://superyachtweb.com

  - name: swancraft.co.uk
    url: https://swancraft.co.uk

  - name: sweatshirt-logos.com
    url: https://sweatshirt-logos.com

  - name: techcorridor.co.uk
    url: https://techcorridor.co.uk

  - name: thecaravanman.org.uk
    url: https://thecaravanman.org.uk

  - name: thegranaries.co.uk
    url: https://thegranaries.co.uk

  - name: themasontrust.org
    url: https://themasontrust.org

  - name: thenorfolkbroadsapp.co.uk
    url: https://thenorfolkbroadsapp.co.uk

  - name: theplaybarn.co.uk
    url: https://theplaybarn.co.uk

  - name: theprivatechefexperience.co.uk
    url: https://theprivatechefexperience.co.uk

  - name: thewigandpen.com
    url: https://thewigandpen.com

  - name: treatnorwich.co.uk
    url: https://treatnorwich.co.uk

  - name: visitnorthnorfolk.co.uk
    url: https://visitnorthnorfolk.co.uk

  - name: visitsuffolk.co.uk
    url: https://visitsuffolk.co.uk

  - name: weddingsguide.co.uk
    url: https://weddingsguide.co.uk

  - name: whalebonefreehouse.co.uk
    url: https://whalebonefreehouse.co.uk

  - name: whitehousefarmholt.co.uk
    url: https://whitehousefarmholt.co.uk

  - name: wroxhamremovals.co.uk
    url: https://wroxhamremovals.co.uk

  - name: yachtfile.com
    url: https://yachtfile.com

  - name: yachtingdomains.com
    url: https://yachtingdomains.com

  - name: yachtingmatters.com
    url: https://yachtingmatters.com

  - name: yuno.co.uk
    url: https://yuno.co.uk

  - name: zambeziresorts.com
    url: https://zambeziresorts.com

  - name: zayohub.com
    url: https://zayohub.com


status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.innershed.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkxheWVyXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IiB3aWR0aD0iMjQyLjVweCIgaGVpZ2h0PSI1OC4zcHgiIHZpZXdCb3g9IjAgMCAyNDIuNSA1OC4zIiBzdHlsZT0iZW5hYmxlLWJhY2tncm91bmQ6bmV3IDAgMCAyNDIuNSA1OC4zOyIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSI+PHN0eWxlIHR5cGU9InRleHQvY3NzIj4uc3Qwe2NsaXAtcGF0aDp1cmwoI1NWR0lEXzJfKTt9LnN0MXtmaWxsOiNGRjM5RDY7fTwvc3R5bGU+PGc+PGRlZnM+PHJlY3QgaWQ9IlNWR0lEXzFfIiB3aWR0aD0iMjI5LjMiIGhlaWdodD0iNTguMyIvPjwvZGVmcz48Y2xpcFBhdGggaWQ9IlNWR0lEXzJfIj48dXNlIHhsaW5rOmhyZWY9IiNTVkdJRF8xXyIgIHN0eWxlPSJvdmVyZmxvdzp2aXNpYmxlOyIvPjwvY2xpcFBhdGg+PGcgY2xhc3M9InN0MCI+PHBhdGggY2xhc3M9InN0MSIgZD0iTTIxNy41LDU0Yy0yLjcsMC00LjEtMS40LTQuMS00LjJWMzAuNWMwLTIuOCwxLjQtNC4yLDQuMS00LjJoNi44djI3LjNDMjIwLjQsNTMuOSwyMTguMiw1NCwyMTcuNSw1NCBNMjI5LjMsMGgtNC45djIyaC04LjFjLTIuMiwwLTQsMC43LTUuNSwyLjJjLTEuNSwxLjUtMi4yLDMuMy0yLjIsNS42djIxLjFjMCwyLjEsMC42LDMuOSwxLjksNS4zYzEuMywxLjQsMywyLjEsNS4xLDIuMWMwLjYsMCwzLjUtMC40LDguOC0xLjJ2MWg0LjlWMHogTTE4NS4xLDI2LjFoMTAuNlYzN2gtMTAuNlYyNi4xeiBNMjAwLjYsNDcuNGgtNC44VjU0aC0xMC42VjQwLjloMTMuN2wxLjctMS43di0xM2MwLTIuOC0xLjQtNC4yLTQuMi00LjJoLTExLjljLTIuOCwwLTQuMiwxLjQtNC4yLDQuMnYyNy43YzAsMi44LDEuNCw0LjIsNC4yLDQuMmgxMS45YzIuOCwwLDQuMi0xLjQsNC4yLTQuMlY0Ny40eiBNMTcyLjQsMjUuOGMwLTIuNy0xLjQtNC00LjEtNGMtMS40LDAtMy40LDAuMi01LjgsMC41Yy0yLDAuMi0zLjksMC41LTUuOSwwLjdWMGgtNC45djU4LjFoNC45VjI2LjdsMTAuOS0wLjN2MzEuN2g0LjlWMjUuOHogTTE0My44LDQ3LjFjMC0xLjctMC42LTMtMS44LTMuOWwtMTMtMTAuNnYtNi4zaDEwdjcuMWg0Ljh2LTcuMmMwLTIuOC0xLjQtNC4yLTQuMi00LjJoLTExLjJjLTIuOCwwLTQuMiwxLjQtNC4yLDQuMnY2YzAsMS42LDAuNiwyLjksMS45LDMuOWwxMi45LDEwLjZ2Ny4yaC0xMHYtOC4xSDEyNHY4LjJjMCwyLjgsMS40LDQuMiw0LjIsNC4yaDExLjNjMi44LDAsNC4yLTEuNCw0LjItNC4yVjQ3LjF6Ii8+PC9nPjxnIGNsYXNzPSJzdDAiPjxwYXRoIGNsYXNzPSJzdDEiIGQ9Ik0xMTgsMjUuOGMwLTIuNy0xLjQtNC00LjEtNGMtMS4zLDAtMywwLjEtNC45LDAuNGMtMS43LDAuMy0zLjMsMC41LTQuOSwwLjh2LTFoLTQuOXYzNi4xaDQuOVYyNi43bDkuMS0wLjN2Ny41aDQuOVYyNS44eiBNNzUuNSwyNi4xaDEwLjZWMzdINzUuNVYyNi4xeiBNOTEsNDcuNGgtNC44VjU0SDc1LjVWNDAuOWgxMy43bDEuNy0xLjd2LTEzYzAtMi44LTEuNC00LjItNC4yLTQuMkg3NC45Yy0yLjgsMC00LjIsMS40LTQuMiw0LjJ2MjcuN2MwLDIuOCwxLjQsNC4yLDQuMiw0LjJoMTEuOWMyLjgsMCw0LjItMS40LDQuMi00LjJWNDcuNHogTTYyLjgsMjUuOGMwLTIuNy0xLjQtNC00LjEtNGMtMS41LDAtMy41LDAuMS01LjksMC40Yy0yLDAuMy0zLjksMC41LTUuOCwwLjh2LTFINDJ2MzYuMWg0LjlWMjYuN2wxMC45LTAuM3YzMS43aDQuOVYyNS44eiBNMzQsMjUuOGMwLTIuNy0xLjQtNC00LjEtNGMtMS41LDAtMy41LDAuMS01LjksMC40Yy0yLDAuMy0zLjksMC41LTUuOCwwLjh2LTFoLTQuOXYzNi4xaDQuOVYyNi43bDEwLjktMC4zdjMxLjdIMzRWMjUuOHogTTQuOSwyMkgwdjM2LjFoNC45VjIyeiIvPjwvZz48ZyBjbGFzcz0ic3QwIj48cG9seWdvbiBjbGFzcz0ic3QxIiBwb2ludHM9IjQuOCwyMC41IDAsMjAuNSAwLDE5LjcgNCwxOS43IDQsMTguMyAwLDE4LjMgMCwxNS40IDQuOCwxNS40IDQuOCwxNi4yIDAuOCwxNi4yIDAuOCwxNy41IDQuOCwxNy41ICIvPjwvZz48L2c+PGc+PGc+PHBhdGggY2xhc3M9InN0MSIgZD0iTTIzOS4yLDMuOWwwLjgsMi40aC0wLjdsLTAuNy0yLjJoLTAuNXYyLjJoLTAuN1YxLjVoMC45YzEsMCwxLjYsMC4zLDEuNiwxLjNDMjM5LjgsMy40LDIzOS42LDMuOCwyMzkuMiwzLjl6IE0yMzguMywyaC0wLjJ2MS42aDAuMmMwLjYsMCwwLjktMC4yLDAuOS0wLjhDMjM5LjIsMi4yLDIzOC44LDIsMjM4LjMsMnoiLz48L2c+PC9nPjxnPjxwYXRoIGNsYXNzPSJzdDEiIGQ9Ik0yMzguNiwwLjZjMS44LDAsMy4zLDEuNSwzLjMsMy4zYzAsMS44LTEuNSwzLjMtMy4zLDMuM2MtMS44LDAtMy4zLTEuNS0zLjMtMy4zQzIzNS4zLDIuMSwyMzYuOCwwLjYsMjM4LjYsMC42IE0yMzguNiwwYy0yLjIsMC00LDEuOC00LDMuOWMwLDIuMiwxLjgsMy45LDQsMy45YzIuMiwwLDMuOS0xLjgsMy45LTMuOUMyNDIuNSwxLjgsMjQwLjgsMCwyMzguNiwwTDIzOC42LDB6Ii8+PC9nPjwvc3ZnPg==
  name: Status
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: Contact
      href: https://innershed.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
